GET http://localhost:1000/api/persons

###
DELETE http://localhost:3001/api/persons/8

###
POST http://localhost:3001/api/persons
Content-Type:application/json


    {
        "name":"Telemann",
        "number":"8010-001 500"
    }

    
